### ISSUE TITLE
Header are send unencoded even though server does not support SMTPUTF8 when mail.mime.allowutf8 is set 

### ISSUE THREAD

**Issue by PascalSchumacher** [eclipse-ee4j/mail#397]
We are using Jakata Mail version `1.6.4` and set the system property `mail.mime.allowutf8=true`.

When commuicating with mailservers that do not support `SMTPUTF8` Jakarta Mail logs  `mail.mime.allowutf8 set but server doesn't advertise SMTPUTF8 support`, but sends headers unencoded anyway e.g. `Reply-To: "öäü" <a@b.com>`.

Doesn't this violate `rfc6531`:

>If the SMTPUTF8 SMTP extension is not offered by the SMTP server, the
 SMTPUTF8-aware SMTP client MUST NOT transmit an internationalized  email address and MUST NOT transmit a mail message containing internationalized mail headers as described in RFC 6532 [RFC6532] at any level within its MIME structure [RFC2045].

source: https://tools.ietf.org/html/rfc6531#page-5

Am I missunderstanding something?

Thanks in advance,
Pascal

**Comment by bshannon** [comment]
The [documentation](https://eclipse-ee4j.github.io/mail/docs/api/javax/mail/internet/package-summary.html#mail.mime.allowutf8) says:


mail.mime.allowutf8 | boolean | If set to "true", UTF-8 strings are allowed in message headers, e.g., in addresses.  This should only be set if the mail server also supports UTF-8.
-- | -- | --


The problem is that the headers are encoded in the MimeMessage.writeTo method,
which doesn't know anything about SMTP or the server that the message is being sent to.
It's up to the application to configure the properties based on the capabilities of the server.

**Comment by PascalSchumacher** [comment]
O.k., thanks for the information. I should have checked the documentation before creating this issue. Sorry.
