### ISSUE TITLE
Missing boundary exception because of -- padding

### ISSUE THREAD

**Issue by gtahp** [eclipse-ee4j/mail#462]
I have a message body(DataSource) with the line `boundary "------=_Part_277834_1226116990.1595356384762"` on the body and content-type header containing `boundary="------=_Part_4_2022398953.1563471830525"`

The problem is that on class [MimeMultipart.java](https://github.com/eclipse-ee4j/mail/blob/master/mail/src/main/java/jakarta/mail/internet/MimeMultipart.java#L586) line 586 there's an addition of "--" to the boundary defined on my header. Because of that addition when comparing the boundary to the line of the body the comparison fails and it keeps looking for the header boundary and fails to find it, throwing an exception at [line 656](https://github.com/eclipse-ee4j/mail/blob/master/mail/src/main/java/jakarta/mail/internet/MimeMultipart.java#L656).

What is the reason that padding is made?

**Comment by jmehrens** [comment]
Can you include a sample test case?

If it is failing at line 656 then you should be able to enable 'mail.mime.multipart. allowempty' property to suppress that per:
https://eclipse-ee4j.github.io/mail/docs/api/javax/mail/internet/package-summary.html

Bill also covered some of this on SO under:
https://stackoverflow.com/questions/13234024/how-to-override-default-unique-boundary-string-and-create-our-own-boundary-using
https://stackoverflow.com/questions/9081739/altering-a-multipart-xxx-content-type-without-altering-the-underlying-parts

As to why the code is this way, I did some digging and the padding has been there at least since version 1.4.1.  I'll see if I can track it to older versions.

7.2.1 Multipart: The common syntax is covered in: https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by gtahp** [comment]
I see that "--" addition even before 1.4.1, back to the oracle implementation and it seems it's expected and exactly like the documentation describes. I found that it already arrives at my code with the header wrong, so in any case I'll give the documentation to the client and see if they're doing something wrong in there.

Thanks a lot @jmehrens
